version: '3.8'
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-ovh
    environment:
      - CONFIG={"settings":[{"provider":"ovh","domain":"ha.jstm.co","host":"*","username":"jstm.co-node","password":"itlmnhnoc","ip_version":"ipv4"},{"provider":"ovh","domain":"portainer.jstm.co","host":"*","username":"jstm.co-node","password":"itlmnhnoc","ip_version":"ipv4"},{"provider":"ovh","domain":"plex.jstm.co","host":"*","username":"jstm.co-node","password":"itlmnhnoc","ip_version":"ipv4"}]}
      - PERIOD=5m
    restart: unless-stopped
    volumes:
      - ./data:/updater/data
    ports:
      - '8001:8000' # Para la interfaz web (opcional)
